import { type Room } from '../_components/RoomCard';

export const ROOMS: Room[] = [
  {
    id: '1',
    slug: 'economy',
    title: 'Економ',
    description: 'Затишний базовий номер для спокійного відпочинку котика.',
    image: '/rooms/economy.jpg',
    gallery: ['/rooms/economy.jpg', '/amenities/photos/none.jpg', '/room1.jpg', '/room2.jpg'],
    size: '90x70x180',
    area: 0.63,
    equipment: ['none'],
    price: 100,
    availableRooms: 4,
  },
  {
    id: '2',
    slug: 'economy-plus',
    title: 'Економ плюс',
    description: 'Більше простору та мʼякий лежак для комфортного сну.',
    image: '/rooms/economy-plus.jpg',
    gallery: [
      '/rooms/economy-plus.jpg',
      '/amenities/photos/bed.jpg',
      '/amenities/photos/scratcher-cat.jpg',
      '/room3.jpg',
    ],
    size: '90x100x180',
    area: 0.9,
    equipment: ['bed', 'scratcher'],
    price: 200,
    availableRooms: 3,
  },
  {
    id: '3',
    slug: 'comfort',
    title: 'Комфорт',
    description: 'Оптимальний номер з ігровою зоною для активних хвостиків.',
    image: '/rooms/comfort.jpg',
    gallery: [
      '/rooms/comfort.jpg',
      '/amenities/photos/bed.jpg',
      '/amenities/photos/scratcher-cat.jpg',
      '/amenities/photos/toy-cat.jpg',
    ],
    size: '100x125x180',
    area: 1.13,
    equipment: ['bed', 'scratcher', 'toy'],
    price: 250,
    availableRooms: 2,
  },
  {
    id: '4',
    slug: 'suite',
    title: 'Сьют',
    description: 'Просторий номер з підвищеним комфортом для довгого проживання.',
    image: '/rooms/suite.jpg',
    gallery: [
      '/rooms/suite.jpg',
      '/amenities/photos/bed.jpg',
      '/amenities/photos/scratcher-cat.jpg',
      '/amenities/photos/toy-cat.jpg',
    ],
    size: '125x125x180',
    area: 1.56,
    equipment: ['bed', 'scratcher', 'toy'],
    price: 350,
    availableRooms: 2,
  },
  {
    id: '5',
    slug: 'lux',
    title: 'Люкс',
    description: 'Преміальний номер з будиночком та ігровим комплексом.',
    image: '/rooms/lux.jpg',
    gallery: [
      '/rooms/lux.jpg',
      '/amenities/photos/house.jpg',
      '/amenities/photos/toy-cat.jpg',
      '/room1.jpg',
    ],
    size: '160x160x180',
    area: 2.56,
    equipment: ['bed', 'scratcher', 'toy', 'house'],
    price: 500,
    availableRooms: 1,
  },
  {
    id: '6',
    slug: 'super-lux',
    title: 'Супер-Люкс',
    description: 'Максимальний простір та топове оснащення для найвибагливіших гостей.',
    image: '/rooms/super-lux.jpg',
    gallery: [
      '/rooms/super-lux.jpg',
      '/amenities/photos/house.jpg',
      '/amenities/photos/toy-cat.jpg',
      '/amenities/photos/scratcher-cat.jpg',
    ],
    size: '180x160x180',
    area: 2.88,
    equipment: ['bed', 'scratcher', 'toy', 'house'],
    price: 600,
    availableRooms: 1,
  },
];

export const AMENITIES = [
  { label: 'Пустий номер', id: 'none' },
  { label: 'Лежак', id: 'bed' },
  { label: 'Кігтеточка', id: 'scratcher' },
  { label: 'Ігровий комплекс', id: 'toy' },
  { label: 'Будиночок', id: 'house' },
] as const;

export const AREAS = ['0,63 м2', '0,90 м2', '1,13 м2', '1,56 м2', '2,56 м2', '2,88 м2'] as const;
