export enum ApiRoutes {
  USERS = '/users',
  CATS = '/cats',
  CAT_REPORTS = '/cat-reports',
  REPORT_IMAGES = '/report-images',
  PERFECT_FOR_ITEMS = '/perfect-for-items',
  ROOM_CATEGORIES = '/room-categories',
  ROOM_CATEGORY_IMAGES = '/room-category-images',
  ROOMS = '/rooms',
  ROOM_AREAS = '/room-areas',
  FEATURES = '/features',
  SERVICES = '/services',
  REVIEWS = '/reviews',
  BOOKING_ITEMS = '/booking-items',
  BOOKING_ITEM_SERVICES = '/booking-item-services',
  BOOKINGS = '/bookings',
  NEWS = '/news',
  VERIFICATION_CODES = '/verification-codes',
}
